config/routes.rb
Rails.application.routes.draw do

  resources :orders
	delete 'orders/:order_id' => 'orders#destroy'

	devise_for :users
  resources :users

  resources :homes
	root :to => "homes#index"

	resources :medium
	resources :magazine_order
	resources :mail_order

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :case
	has_many :magazine_orders, foreign_key: 'order_id'
	has_many :mail_orders, foreign_key: 'order_id'
	self.inheritance_column = :_type_disabled # using a name of column "type" in table
#	validates :user_id, presence: true
	attr_accessor :media_mag, :media_web, :media_mail

	#order category
	MAGAZINE_SCHEME = 0
	WEB_SCHEME = 1
	MAIL_SCHEME = 2
end

app/controllers/orders_controller.rb
require 'viewpoint'
include Viewpoint::EWS

class OrdersController < ApplicationController
#  before_action :set_order, only: :create
  respond_to :html

  def index
	@cases = Case.where(pic_id: current_user.id)
	respond_with(@orders)
  end

  def show
  	@order = Order.find(params[:id])
	@case = Case.find(@order.case_id)
	#@mag = MagazineOrder.find_by_order_id(@order.id)
	@media_type = mediatype(@order)
	if @order.category == Order::MAGAZINE_SCHEME
		@mag = @order.magazine_orders.first
	elsif @order.category == Order::MAIL_SCHEME
		@mail = @order.mail_orders.first
	end
	@case_status = casestatus(@case)
	respond_with(@order)
  end

  def new
	respond_with(@order)
  end

  def edit
		@order = Order.find(params[:id])
		@case = Case.find(@order.case_id)
		respond_with(@order)
  end

  def create 
	@case = Case.new(case_params)
	@case.pic_id = current_user.id
	@case.save

 	@order = Order.new(order_params)
	@order.case_id = @case.id
	@order.save
	@media = createmedia(@order)
   	    	
	if params[:mail][:send] == "1"
		sendmail(@case,@order,@media)
	end
	redirect_to orders_path
	flash[:success] = "オーダーを登録しました"
  end

  def update
	@order = Order.find(params[:id])
	@case = Case.find(@order.case_id)
	
	@media_type = mediatype(@order)
	
	@order.update(order_params)
	@case.update(case_params)
	@media = updatemedia(@order)
	if params[:mail][:send] == "1"
		#Mailer.sendmail(@order).deliver
		sendmail(@case,@order,@media)
	end
	redirect_to orders_path
	flash[:success] = "オーダーを編集しました"
  end

def destroy
	o = Order.find(params[:id])
	c = Case.find(o.case_id)
	c.destroy
	o.destroy
	flash[:success] = "オーダーを削除しました"
	redirect_to orders_path
end

private
def casestatus(c)
	@case = c
	@case_status = nil
	if @case.status == Case::OK_SCHEME
		@case_status = "決定"
	elsif @case.status == Case::ALMOST_SCHEME
		@case_status = "角度高め"
	elsif @case.status == Case::PROPOSING_SCHEME
		@case_status = "提案中"
	end
	return @case_status
end

def mediatype(order)
	@order = order
	@media_type = nil
	if@order.category == Order::MAGAZINE_SCHEME
		@media_type = "雑誌広告"
	elsif @order.category == Order::WEB_SCHEME
		@media_type = "インターネット広告"
	elsif @order.category == Order::MAIL_SCHEME
		@media_type = "メール広告"
	end
	return @media_type
end

def createmedia(order)
	@order = order
    	if @order.category == Order::MAGAZINE_SCHEME
    		@order.media = order_params[:media_mag] 
    		@order.save
    		@mag = MagazineOrder.new(mag_params)
    		@mag.order_id = @order.id
    		@mag.save
    		pp @mag
    		return @mag
    	elsif  @order.category == Order::WEB_SCHEME
    		@order.media = order_params[:media_web]
    	elsif  @order.category == Order::MAIL_SCHEME
    		@order.media = order_params[:media_mail]
    		@order.save
    		@mail = MailOrder.new(mail_params)
    		@mail.order_id = @order.id
    		@mail.save
    		pp @mail
    		return @mail
    	end
end

def updatemedia(order)
	@order = order
    	if @order.category == Order::MAGAZINE_SCHEME
    		@order.media = order_params[:media_mag] 
    		@order.save
    		@mag = MagazineOrder.find_by_order_id(@order.id)
     		@mag.order_id = @order.id
    		@mag.update(mag_params)
    		return @mag
    	elsif  @order.category == Order::WEB_SCHEME
    		@order.media = order_params[:media_web]
    	elsif  @order.category == Order::MAIL_SCHEME
    		@order.media = order_params[:media_mail]
		@order.save
    		@mail = MailOrder.find_by_order_id(@order.id)
    		@mail.order_id = @order.id
    		@mail.update(mail_params)
    		return @mail
    	end
end

def sendmail(c,o,m)
	@case = c
	@order = o
	@media = m

	t = render_to_string('mail.text.erb', collection: [@case, @order, @media]).to_str
	cli = Viewpoint::EWSClient.new endpoint, user, pass

	cli.send_message do |m|
		m.subject = "【申込み】"+ Medium.find_by_shorten(@order.media).name+":"+@case.client
		m.body = t
		m.to_recipients << ''
		m.cc_recipients << current_user.email
	end
end

def case_params
params.require(:case).permit(:name, :client, :agent, :pic_id, :status)
end

def order_params
	params.require(:order).permit(:media, :price, :margin, :rate, :notes, :media_mag, :media_web, :media_mail, :management_number, :month_of_bill, :address_of_bill, :case_id, :category)
end

def mag_params
	params.require(:magazine_order).permit(:order_id, :issue, :release_date, :space, :ad_form, :production_costs, :production, :montgh_of_appropriation)
end

def mail_params
	params.require(:mail_order).permit(:send_date, :space)
end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>オーダー情報を変更</h1>

<%= form_for(@order, :url=>{:action => 'update'}, :html=>{:method =>:put}) do %>
<ul style="list-style:none;">
	<li>
		状況 <%= select :case, :status, {"決定"=>0, "角度高め"=>1, "提案中"=>2} %>
	</li>
	
	<% if @order.category == Order::MAGAZINE_SCHEME %>	
		<li>
			媒体名
			<%= select :order, :media_mag, Medium.where(:category=>0).map{|m| [m.name, m.shorten]} %>
		</li>
		<li>
			掲載号発売日
			<%= date_field("magazine_order", "release_date")%>
		</li>
	<% elsif @order.category == Order::WEB_SCHEME %>
		<li>
			媒体名
			<%= select :order, :media_mag, Medium.where(:category=>0).map{|m| [m.name, m.shorten]} %>		</li>
		<li>
			掲載期間:
			<%= date_field("order", "start_date")%> - <%= date_field("order", "end_date")%>
		</li>
	<% elsif @order.category == Order::MAIL_SCHEME %>
		<li>
			媒体名
			<%= select :order, :media_mail, Medium.where(:category=>2).map{|m| [m.name, m.shorten]} %>
		</li>
		<li>
			配信日
			<%= date_field("mail_order", "send_date")%>
		</li>
		<li>
			スペース 
			<%= select :mail_order, :space, Space.where(:category=>2).map{|s| [s.name]} %>
		</li>

	<% end %>
	
	<li>
		広告主  <%= text_field "case", :client %>
	</li>
	<li>
		広告会社 <%= text_field "case", :agent %>
	</li>
	<li>
		料金 <%= text_field "order", :price %>万円
	</li>
	<li>
		マージン<%= select :order, :rate, {"15%"=>15, "20%"=>20} %>
	</li>
	<li>
		レート <%= select :order, :rate, {"1回"=>1, "3回"=>3} %>
	</li>
	<li>
		請求先 <%= text_field "order", :address_of_bill %>
	</li>
	<li>
		備考 <%= text_field "order", :notes %>
	</li>

	<% if current_user.role == 0 %>
	<% elsif current_user.role == 1 %>
	<% elsif current_user.role == 2 %>
	<li>
		管理番号 <%= text_field "order", :management_number %>
	</li>
	<% end %>
	<li>
		オーダー情報をメールで送信する <%= check_box "mail", "send" %>
	</li>
</ul>
<%= submit_tag '再登録する', :user_id => current_user.id %>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= current_user.name %>さんのオーダー一覧</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
	<tr>
		<th>　</th>
		<th>案件名</th>
		<th>掲載媒体</th>
		<th>広告主</th>
		<th>広告会社</th>
	</tr>

	<% @cases.each do |c| %>
		<% orders = Order.where(case_id: c.id) %>
			<% orders.each do |o| %>
			<tr>
			<td><%= link_to '詳細', o %></td>
			<th><%= c.name %></th>
			<th><%= o.media %></th>
			<th><%= c.client %></th>
			<th><%= c.agent %></th>
			<tr>
		<% end %>
	<% end %>
  </tbody>

</table>

<br>

app/views/orders/mail.text.erb
※本メールは、広告オーダーシステムからの自動送信メールです。


ご担当者様

お疲れ様です。
下記申込がございましたので、ご確認ください。
よろしくお願いいたします。

【記入日時】<%= @case.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[@case.created_at.wday]})") %>
***********************************************************

【広告掲載申込情報】
---------------------------------------------------------------------

【案件名】<%= @case.name %>
【広告主】<%= @case.client %>
【広告会社】<%= @case.agent %>
【掲載媒体】<%= @order.media %>
【申込金額】<%= @order.price %>万円
【金額レート】<%= @order.rate %>回レート
【マージン】<%= @order.margin %>%

<% if @order.category == Order::MAGAZINE_SCHEME %>
<% if @media.ad_form == true %>
【発売日】<%= @media.release_date %>
【スペース】<%= @media.space %>
<% end %>
<% elsif @order.category == Order::WEB_SCHEME %>
<% elsif @order.category == Order::MAIL_SCHEME %>
【配信日】<%= @media.send_date %>
【スペース】<%= @media.space %>
<% end %>

【請求月】<%= @order.month_of_bill %>
【請求書送付先】<%= @order.address_of_bill %>

【管理番号】<%= @order.management_number %>
【備考】<%= @order.notes %>
---------------------------------------------------------------------
***********************************************************

app/views/orders/new.html.erb
<script type="text/javascript">
$(function(){
$('#order_category').change(function() {
	if ($('#order_category option:selected').val() == 0) 
		$('#div_mag').css('display','table-row') && $('#div_web').css('display','none') && $('#div_mail').css('display','none');
	//else if ($('#order_category option:selected').val() == 1) 
		//$('#div_web').css('display','table-row') && $('#div_mag').css('display','none')&& $('#div_mail').css('display','none');
	else if ($('#order_category option:selected').val() == 2) 
		$('#div_mail').css('display','table-row') && $('#div_mag').css('display','none')&& $('#div_web').css('display','none');
	 });
});

function onButtonClick() {
	$('#div_space').css('display','table');
}
</script>
<br />
<h1>新規オーダー情報</h1>

<%= form_tag :action => :create do %>
<ul style="list-style:none;">
	<li>
		<%= select :order, :category, {"雑誌"=>0, "Web（動きません）"=>1, "メール"=>2} %>
	</li>
	<li>
		案件名 <%= text_field "case", :name %>
	</li>
	<li>
		状況 <%= select :case, :status, {"決定"=>0, "角度高め"=>1, "提案中"=>2} %>
	</li>

	<div id ="div_mag">
		<li>
			媒体名
			<%= select :order, :media_mag, Medium.where(:category=>0).map{|m| [m.name, m.shorten]} %>
		</li>
		<li>
			掲載号発売日
			<%= date_field("magazine_order", "release_date")%>
		</li>
		<li>
			スペース 
			<%= select :magazine_order, :space, Space.where(:category=>0).map{|s| [s.name]} %>
			 <input type="checkbox" onClick="onButtonClick()">
			 <div id = "div_space" style="display: none;" align="left">
				 <%= text_field "order", :price %>
			 </div>
		</li>
		<li>
			 純広告 or タイアップ <%= select :magazine_order, :ad_form,  {"純広告"=>true, "タイアップ"=>false} %>
		</li>
		<li>
			 制作会社 <%= text_field "magazine_order", :production %>
		</li>
		<li>
			 制作費 <%= text_field "magazine_order", :production_costs %>
		</li>
	</div>

	<div id="div_web" style="display: none;">
		<li>
			媒体名
			<%= select :order, :media_web, Medium.where(:category=>1).map{|m| [m.name, m.shorten]} %>
		</li>
	</div>

	<div id="div_mail" style="display: none;">
		<li>
			媒体名
			<%= select :order, :media_mail, Medium.where(:category=>2).map{|m| [m.name, m.shorten]} %>
		</li>
		<li>
			配信日
			<%= date_field("mail_order", "send_date")%>
		</li>
		<li>
			スペース 
			<%= select :mail_order, :space, Space.where(:category=>2).map{|s| [s.name]} %>
		</li>
	</div>
	
	<li>
		広告主  <%= text_field "case", :client %>
	</li>
	<li>
		広告会社 <%= text_field "case", :agent %>
	</li>
	<li>
		料金 <%= text_field "order", :price %>万円
	</li>
	<li>
		マージン<%= select :order, :margin, {"15%"=>15, "20%"=>20} %>
	</li>
	<li>
		レート <%= select :order, :rate, {"1回"=>1, "3回"=>3} %>
	</li>
	<li>
		請求先 <%= text_field "order", :address_of_bill %>
	</li>
	<li>
		備考 <%= text_field "order", :notes %>
	</li>
	<li>
		オーダー情報をメールで送信する <%= check_box "mail", "send" %>
	</li>
</ul>
<%= submit_tag '申し込む', :user_id => current_user.id %>
<% end %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h1>オーダー情報</h1>

<%= @order.created_at.strftime("%Y年%m月%d日") %>に登録された
<%= @media_type %>
のオーダーです。

<ul style="list-style:none;">
	<li>状況:<%= @case_status %><li>
	<li>媒体:<%= @order.media %></li>
	
	<% if @order.category == Order::MAGAZINE_SCHEME %>
		<li>発売日:<%= @mag.release_date %></li>
		<li>スペース:<%= @mag.space %>
		<% if @mag.ad_form == true %>
			※純広告</li>
		<% else %>
			※タイアップ</li>
		<% end %>
		<li>制作会社:<%= @mag.production %></li>
		<li>制作費:<%= @mag.production_costs %></li>
		
	<% elsif @order.category == Order::WEB_SCHEME %>
	<% elsif @order.category == Order::MAIL_SCHEME %>
		<li>配信日:<%= @mail.send_date %></li>
		<li>スペース:<%= @mail.space %></li>
	<% end %>
	
	<li>金額:<%= @order.price %>万円</li>
	<li>広告主:<%= @case.client %></li>
	<li>広告会社:<%= @case.agent %></li>
	<li>マージン:<%= @order.margin %>%</li>
	<li>備考:<%= @order.notes %></li>
</ul>

<%= link_to '編集', edit_order_path(@order) %> |
<%= link_to '削除', @order, method: :delete, data: { confirm: '本当に削除しますか？' } %> |
<%= link_to '戻る', orders_path %>